unit Cloud.Model.RetornoJson;

{*******************************************************************************
    Generated By   : JsonToDelphiClass - 0.65
    Project link   : https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
    Generated On   : 2019-11-18 15:29:53

    Created By     : Petar Georgiev - (http://pgeorgiev.com)
    Adapted Web By : Marlon Nardi - (http://jsontodelphi.com)
*******************************************************************************}

interface

uses Generics.Collections, Rest.Json, Cloud.Dto.Tabela;

type

TCloudRetornoJson = class(TCloudTabela)
private
  FDescricao: String;
  FTipo: String;
  FTitulo: String;
public
  property descricao: String read FDescricao write FDescricao;
  property tipo: String read FTipo write FTipo;
  property titulo: String read FTitulo write FTitulo;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TCloudRetornoJson;
end;

implementation

{TCloudRetornoJson}


function TCloudRetornoJson.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TCloudRetornoJson.FromJsonString(AJsonString: string): TCloudRetornoJson;
begin
  result := TJson.JsonToObject<TCloudRetornoJson>(AJsonString)
end;

end.
